Technical => main
algosup/2024-2025-project-1-fpga-team-2 pull request #9
Opened 2024-10-11 13:19 UTC by Mattstar64

Final version of the Technical specification, also including naming conventions.

2024-10-11 14:36 UTC, GuillaumeDespaux requested changes
On ./technical/naming_conventions_and_review.md :
- minuscule is a French word
- Line 32 "exmple" (typo)

./technical/technical_specification.md :
- Missing date for Finished
- L19 to L24 Capital letter missing on some letters
- L48 "technologie's" (typo)
- L53 "movement" (typo)
- L58 "wining" (typo)
- L61 "high scores" (typo)
- L80 not the objective
- L103 "-" error
- L115 & L118 you don't apply your own rule
- L122 & L126 //
- L130 Ok only if script to lunch the game else in ./src/
- L131 typo
- L143 not English -> At least "In technical details"
- L149 "developpement" (typo)
- L165 Switches -> switches
- L166 show -> display
- L167 -> current level.
- L185 check for another way to say it (we render)
- L193 image? not pixel?
- L218 remove the "The" to put "Differents cars"
- L246 French commentary
- L279
- L281 & L283 use Up and Down
- L313 Movements
- L334 & 338 & 340 why dot at the end ?
- L349 begin -> start
- L351 bins -> the trash cans
- L391 & L393 high scores (typo)

2024-10-11 14:38 UTC, EnoGame29 requested changes
- In the naming_conventions_and_rules, you wrote "Varibles" instead of "Variables" (line 19)
- In the 4fh dot of 2.2 in technical_spec, there are a useless dash before "Team Members"
- In your file structure, the README is written like that "READEME"
- You've forgotten the "Go" for the Lenovo Thinkpad between 512 and SSD
- You wrote (3.4, B) "o control" instead of "To control" at the first line
- In the description of the 4th code, you wrote "whre switches" instead of "where switches"
- You've forgotten a 'o' at "loose" (so 'lose') in the C sections

2024-10-11 15:30 UTC, Mattstar64 commented
fixed

2024-10-11 20:06 UTC, EnoGame29 requested changes
- Line 149, "developpement" is a French word, try to use "development" 
- Lines 151 & 152, the two lines used "Code ..." instead of "Core"
- Line 155, you can put a lower case in "Screen" **(Screen -> screen)**
- Line 163, you can use a mark after "On this board"
- Line 167, put "the" before "current score"
- Line 177 : 
 - You can joined "set" and "up" ("set up" -> "setup")
 - The "the" before the link is too much
 - You can use "the" before "Nandland website"
- Line 187, the 's' of "sync" in "V_Sync_Pulse" can be in capital letter
- Line 216 and 277, you can put a dot after the letters 
- Line 366, my bad, loose is the adjective or we need to use the verb

2024-10-11 20:06 UTC, Enonome commented on documents/technical/technical_specification.md
> +   - [**D. Points and high score**](#d-points-and-high-scores)
Problem with redirection (not the right tag)

2024-10-11 20:06 UTC, Enonome commented on documents/technical/technical_specification.md
> +1.4| 10/10/2024|Mattéo LEFIN| - Finished writing <br> - added winning/loosing schema <br> - Added all code|
You can also put a capital letter on the 1st "added"

added -> Added

2024-10-11 20:06 UTC, Enonome commented on documents/technical/technical_specification.md
> +1.2| 10/02/2024|Mattéo LEFIN| - Remade the Table of content <br> - finished 3.1/2/3.B |
You can put a capital letter on "finished" too

finished -> Finished

2024-10-11 20:06 UTC, Enonome commented on documents/technical/technical_specification.md
>     - [**A. Wining and loosing mechanics**](#a-winning-and-loosing-mechanics)
"Wining" takes two 'n'

wining -> winning

2024-10-11 20:06 UTC, Enonome commented on documents/technical/technical_specification.md
>  <summary>3. Into technicalities</summary>
Change the name of the summary in order to correspond with the current name of the 3.

Into technicalities -> in technical details

2024-10-11 20:06 UTC, Enonome commented on documents/technical/technical_specification.md
>  - LENOVO ThinkPad 21JKCTO1WW - Core i7 - 16 Go RAM - 512 SSD
Missing the "Go" for Giga octet between 512 and SSD

2024-10-12 11:12 UTC, Mattstar64 commented on documents/technical/technical_specification.md
>  - LENOVO ThinkPad 21JKCTO1WW - Core i7 - 16 Go RAM - 512 SSD
the Go isn't placed here for this one, it's actually normal

2024-10-12 11:17 UTC, Mattstar64 commented on documents/technical/technical_specification.md
>  <summary>3. Into technicalities</summary>
Already done ?

2024-10-12 11:31 UTC, EnoGame29 commented on documents/technical/technical_specification.md
>  - LENOVO ThinkPad 21JKCTO1WW - Core i7 - 16 Go RAM - 512 SSD
Okay 👍

2024-10-12 11:35 UTC, EnoGame29 commented on documents/technical/technical_specification.md
> +   - [**D. Points and high score**](#d-points-and-high-scores)
Fixed

2024-10-12 11:40 UTC, EnoGame29 commented on documents/technical/technical_specification.md
>  <summary>3. Into technicalities</summary>
Yeah, probably a display issue when reviewing

2024-10-12 17:08 UTC, EnoGame29 requested changes
My last overall review did not verify (note there is a new pending comment)

2024-10-12 17:08 UTC, EnoGame29 commented on documents/technical/technical_specification.md
> +For this project, we used for developpment :
There is an extra 'p' in "developpment'

(developpment -> development)

2024-10-12 17:46 UTC, EnoGame29 approved these changes
Everything is good for me

2024-10-13 13:10 UTC, GuillaumeDespaux approved these changes
Ok for me.

2024-10-13 13:10 UTC, merged